# Generated by Django 3.2.19 on 2023-05-26 09:21

from django.db import migrations, models
import django.db.models.deletion
import voteit.core.abcs
import voteit.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisation', '0009_auto_20230525_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('active', models.BooleanField(default=True, verbose_name='Is this type active?')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Year')),
                ('payed', models.BooleanField(default=False, verbose_name='Payed?')),
                ('canceled', models.BooleanField(default=False, verbose_name='Canceled?')),
                ('text', models.TextField(blank=True, default='', verbose_name='Comments')),
                ('membership_type', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='voteit_org.membershiptype', verbose_name='Membership Type')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='memberships', to='organisation.organisation', verbose_name='Organisation')),
            ],
            options={
                'ordering': ['-year'],
                'get_latest_by': '-year',
            },
            bases=(voteit.core.abcs.AuditLogMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', voteit.core.fields.RichTextField(blank=True, default='', verbose_name='Contact text or other notes')),
                ('generic_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Generic contact email')),
                ('invoice_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Invoice email')),
                ('invoice_info', voteit.core.fields.RichTextField(blank=True, default='', verbose_name='Invoice info/address')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('requires_check', models.BooleanField(default=False, verbose_name='Requires check from organisation')),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='contact_info', to='organisation.organisation', verbose_name='Organisation')),
            ],
            options={
                'abstract': False,
            },
            bases=(voteit.core.abcs.AuditLogMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('organisation', 'year'), name='unique_membership_year'),
        ),
    ]
