# Generated by Django 3.2.19 on 2023-05-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteit_org', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='payed',
        ),
        migrations.AddField(
            model_name='membership',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Paid?'),
        ),
    ]
