# Generated by Django 3.2.19 on 2023-05-30 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voteit_org', '0002_auto_20230530_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='voteit_org.membershiptype', verbose_name='Membership Type'),
        ),
    ]
