# Generated by Django 4.2.15 on 2024-12-03 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("voteit_org", "0003_alter_membership_membership_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="membership",
            name="canceled",
        ),
    ]
